# Duplicated from posable.cabal
- arguments:
  - "-XNoStarIsType"
  - "-XDataKinds"
  - "-XTypeApplications"
  - "-XTypeOperators"
  - "-XScopedTypeVariables"
  - "-XTypeFamilies"
  - "-XGADTs"
  - "-XDeriveAnyClass"
