name: "Build & Test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Cache Stack files"
      uses: actions/cache@v2.1.7
      with:
        path: |
          .stack-work
          ~/.local/bin/stylish-haskell
        key: ${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack

    - name: "Install Stack"
      run: "sudo apt-get -y install haskell-stack"

    - name: "Get stylish-haskell"
      run: "curl https://github.com/haskell/stylish-haskell/releases/download/v0.13.0.0/stylish-haskell-v0.13.0.0-linux-x86_64.tar.gz -o stylish-haskell.tar.gz"

    - name: "Untar stylish-haskell"
      run: "tar xzf stylish-haskell.tar.gz"

    - name: "add stylish-haskell to PATH"
      run: "echo 'stylish-haskell-v0.13.0.0-linux-x86_64/stylish-haskell' >> $GITHUB_PATH"

    - name: "Run linter"
      run: "./stylish-haskell.sh"

    - name: "Install dependencies"
      run: "stack install"

    - name: "Build"
      run: "stack build"

    - name: "Run tests"
      run: "stack test"
